### specify the name of an existing secret that contains the ogg admin username and password
ogg:
  adminSecret: ogg-admin-secret
  usernameKey: oggusername
  passwordKey: oggpassword
  ## the name of an OGG deployment, mostly "local", or ogg-east, ogg-west, ...
  deploymentName: local

## request sizes of some PVCs, beware that there can be many   big trail files ...
storage:
  configSize: 1Gi
  logSize: 10Gi
  trailSize: 50Gi

image:
  pullPolicy: IfNotPresent
  imageName: container-registry.oracle.com/goldengate/goldengate-postgresql:23.10.3.25.11
  secretName: container-registry-secret

statsdExporter:
  enabled: false

services:
  ### a clusterIP type service will be created for graph and jupyter UIs.
  ### You can choose to create an istio virtualservice or an ingress in front of it
  ### with a virtual host name of ggate.<suffix>
  external:
    ### set type to either ingress , virtualservice or none if You need something customized
    type: ingress
    ### typical ingressClasses are nginx and istio
    ingressClass: nginx
    ### ignored if type is not virtualservice
    vserviceGateway: istio-system/http-istio-gateway
    ### uses default SSL certificate of gateway/controller or specify a custom tls-secret here
    tlsSecretName: ggate-tls-secret
    vhostName: ggate.xxx.xxx.xxx.xxx.nip.io
  internal:
    type: ClusterIP

resources:
  requests:
    cpu: "1"
    memory: 2Gi
  limits:
    cpu: "2"
    memory: 16Gi

